document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/nguyen-tuan-quynh/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Nguyễn Tuấn Quỳnh"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Nguyễn-Tuấn-Quỳnh.jpg'");
document.querySelector('img[alt="Nguyễn Tuấn Quỳnh"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Nguyễn-Tuấn-Quỳnh-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/bjorn-lee/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Bjorn Lee"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Bjorn-Lee.jpg'");
document.querySelector('img[alt="Bjorn Lee"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Bjorn-Lee-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/ishan-agrawal/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Ishan Agrawal"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Ishan-Agrawal.jpg'");
document.querySelector('img[alt="Ishan Agrawal"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Ishan-Agrawal-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/le-yen-thanh/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Lê Yên Thanh"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Lê-Yên-Thanh.jpg'");
document.querySelector('img[alt="Lê Yên Thanh"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Lê-Yên-Thanh-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/dominik-weil/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Dominik Weil"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Dominik-Weil.jpg'");
document.querySelector('img[alt="Dominik Weil"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Dominik-Weil-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tom-kosnik/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Tom Kosnik"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tom-Kosnik-.jpg'");
document.querySelector('img[alt="Tom Kosnik"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tom-Kosnik-1-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tran-nhat-khanh/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-09.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-09.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-09.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Trần Nhật Khanh"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Trần-Nhật-Khánh.jpg'");
document.querySelector('img[alt="Trần Nhật Khanh"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Trần-Nhật-Khánh-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/duong-thu-huong/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-08.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-08.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-08.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Đường Thu Hương"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Đường-Thu-Hương.jpg'");
document.querySelector('img[alt="Đường Thu Hương"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Đường-Thu-Hương-1.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/ngo-thuy-ngoc-tu/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-10.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-10.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-10.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Ngô Thùy Ngọc Tú"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-11.jpg'");
document.querySelector('img[alt="Ngô Thùy Ngọc Tú"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Tú-Ngô.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/cuong-nguyen/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-11.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-11.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-11.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Cường Nguyễn"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-09.jpg'");
document.querySelector('img[alt="Cường Nguyễn"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Cường-Nguyễn.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/logan-leung/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-12.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-12.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-12.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Logan Leung"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-10.jpg'");
document.querySelector('img[alt="Logan Leung"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/logan-leung.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/nguyen-viet-duc/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-13.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-13.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-13.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Nguyễn Việt Đức"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-13.jpg'");
document.querySelector('img[alt="Nguyễn Việt Đức"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Nguyễn-Việt-Đức.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tran-ngoc-thai-son/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-14.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-14.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-14.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Trần Ngọc Thái Sơn"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-12.jpg'");
document.querySelector('img[alt="Trần Ngọc Thái Sơn"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Trần-Ngọc-Thái-Sơn.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tony-ha/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC_15.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC_15.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC_15.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Tony Ha"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Tony-Ha-14.jpg'");
document.querySelector('img[alt="Tony Ha"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Tony-Ha-bw.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/ronald-le/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC-16.png");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC_16.png"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/speaker_TUBMC_16.png"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Ronald Le"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-15.png'");
document.querySelector('img[alt="Ronald Le"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/08/Speaker_HomeImage-15_wb.png'");

$(document).ready(function() {
$("a.fancylink").fancybox();
});
