document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/nguyen-tuan-quynh/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-02.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Nguyễn Tuấn Quỳnh"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Nguyễn-Tuấn-Quỳnh.jpg'");
document.querySelector('img[alt="Nguyễn Tuấn Quỳnh"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Nguyễn-Tuấn-Quỳnh-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/bjorn-lee/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-03.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Bjorn Lee"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Bjorn-Lee.jpg'");
document.querySelector('img[alt="Bjorn Lee"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Bjorn-Lee-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/ishan-agrawal/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-04.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Ishan Agrawal"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Ishan-Agrawal.jpg'");
document.querySelector('img[alt="Ishan Agrawal"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Ishan-Agrawal-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tomithy-too/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-05.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-05.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-05.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Tomithy Too"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tomithy-Too.jpg'");
document.querySelector('img[alt="Tomithy Too"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tomithy-Too-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/le-yen-thanh/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-07.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Lê Yên Thanh"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Lê-Yên-Thanh.jpg'");
document.querySelector('img[alt="Lê Yên Thanh"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Lê-Yên-Thanh-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/dominik-weil/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/speaker_TUBMC-06.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Dominik Weil"').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Dominik-Weil.jpg'");
document.querySelector('img[alt="Dominik Weil"').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Dominik-Weil-1-500x500.jpg'");
document.querySelector('a[href="http://bootcamp2018.vye.vn/speaker/tom-kosnik/"]').setAttribute("href", "http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg");
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg"]').classList.add('fancylink');
document.querySelector('a[href="http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/poster_the-ultimate-business-master-class-03.jpg"]').setAttribute("onclick", '$("a.fancylink").trigger("click");');
document.querySelector('img[alt="Tom Kosnik"]').setAttribute("onmouseover", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tom-Kosnik-.jpg'");
document.querySelector('img[alt="Tom Kosnik"]').setAttribute("onmouseout", "this.src='http://bootcamp2018.vye.vn/wp-content/uploads/2018/07/Tom-Kosnik-1-1-500x500.jpg'");
$(document).ready(function() {
$("a.fancylink").fancybox();
});
